trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: Thivagar007.HTS-L2-CS001
      trigger: true

variables:
  acrLoginServer: 'htsl2cs01.azurecr.io'
  imageName: 'snakegameapp'
  tag: $(resources.pipeline.ciPipeline.runName)

stages:
  - stage: Deploy_Dev
    displayName: Deploy to Dev
    jobs:
      - deployment: DeployDev
        displayName: Deploy to AKS - Dev
        environment: 'dev'
        pool:
          name: 'vmss-agent'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    sed -i 's#__IMAGE_TAG__#$(tag)#g' k8s/deployment.yml
                  displayName: Replace image tag

                - task: Kubernetes@1
                  displayName: Apply Kubernetes Manifests (Dev)
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: 'HTS-L2-AKS-SC'
                    azureResourceGroup: 'HTS-L2-CS001-RG'
                    kubernetesCluster: 'HTS-L2-CS001-AKS'
                    namespace: 'dev'
                    command: 'apply'
                    useConfigurationFile: true
                    configuration: 'k8s/deployment.yml'
                    secretType: 'None'

  - stage: Deploy_Test
    displayName: Deploy to Test
    dependsOn: Deploy_Dev
    condition: succeeded()
    jobs:
      - deployment: DeployTest
        displayName: Deploy to AKS - Test
        environment: 'test'
        pool:
          name: 'vmss-agent'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    sed -i 's#__IMAGE_TAG__#$(tag)#g' k8s/deployment.yml
                  displayName: Replace image tag

                - task: Kubernetes@1
                  displayName: Apply Kubernetes Manifests (Test)
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: 'HTS-L2-AKS-SC'
                    azureResourceGroup: 'HTS-L2-CS001-RG'
                    kubernetesCluster: 'HTS-L2-CS001-AKS'
                    namespace: 'test'
                    command: 'apply'
                    useConfigurationFile: true
                    configuration: 'k8s/deployment.yml'
                    secretType: 'None'

  - stage: Deploy_Prod
    displayName: Deploy to Prod
    dependsOn: Deploy_Test
    condition: succeeded()
    jobs:
      - deployment: DeployProd
        displayName: Deploy to AKS - Prod
        environment: 'prod'
        pool:
          name: 'vmss-agent'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    sed -i 's#__IMAGE_TAG__#$(tag)#g' k8s/deployment.yml
                  displayName: Replace image tag

                - task: Kubernetes@1
                  displayName: Apply Kubernetes Manifests (Prod)
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: 'HTS-L2-AKS-SC'
                    azureResourceGroup: 'HTS-L2-CS001-RG'
                    kubernetesCluster: 'HTS-L2-CS001-AKS'
                    namespace: 'prod'
                    command: 'apply'
                    useConfigurationFile: true
                    configuration: 'k8s/deployment.yml'
                    secretType: 'None'