trigger:
  branches:
    include:
      - main

variables:
  imageName: 'snakegameapp'
  containerRegistry: 'HTS-L2-ACR-SC'
  tag: '$(Build.BuildId)'
  javaVersion: '17'
  javaHome: '/usr/lib/jvm/java-17-openjdk-amd64'

stages:
  - stage: Build
    displayName: 'Build and Package'
    jobs:
      - job: Build
        displayName: 'Build Java App and Push Docker Image'
        pool:
          name: 'vmss-agent'
          demands:
            - agent.os -equals Linux

        steps:
          # Install JDK
          - script: |
              sudo apt-get update -y
              sudo apt-get install -y openjdk-$(javaVersion)-jdk docker.io
              echo "JAVA_HOME=$(javaHome)" | sudo tee -a /etc/environment
              echo "##vso[task.setvariable variable=JAVA_HOME]$(javaHome)"
              echo "##vso[task.prependpath]$(javaHome)/bin"
              java -version
            displayName: 'Install JDK and Docker'

          # Maven build
          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests=false'
              publishJUnitResults: true
              testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
              javaHomeOption: 'Path'
              jdkDirectory: '$(javaHome)'

          # Verify build output
          - script: |
              echo "Artifacts in target:"
              find target -name "*.jar"
            displayName: 'Verify JAR Output'

          # Publish JAR
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              PathtoPublish: 'target/snakegame-0.0.1-SNAPSHOT.jar'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          # Docker login
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: 'login'
              containerRegistry: '$(containerRegistry)'

          # Build and push Docker image
          - task: Docker@2
            displayName: 'Build and Push Image'
            inputs:
              containerRegistry: '$(containerRegistry)'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(tag)'
