trigger:
  branches:
    include:
      - main

variables:
  imageName: 'springboot-app'
  tag: '$(Build.BuildId)'

pool:
  name: 'my-agent'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs: 
      - job: Build
        displayName: 'Build Job'
        steps:
          - task: Maven@2
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              sonarQubeRunAnalysis: false
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'jar'
              publishLocation: 'pipeline'

  - stage: DockerPush
    displayName: 'Docker Build and Push'
    dependsOn: Build
    jobs:
      - job: BuildAndPush
        displayName: 'Build and Push Docker Image'
        steps:
          - task: Docker@2
            inputs:
              command: 'buildAndPush'
              repository: '$(imageName)'
              dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
              containerRegistry: 'HTS-L2-ACR-SC'