trigger:
  branches:
    include:
      - main

pool:
  name: 'my-agent'

variables:
  imageName: 'snakegameapp'
  containerRegistry: 'HTS-L2-ACR-SC'
  tag: '${Build.BuildId}'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              javaHomeOption: 'JDKVersion'
              JDKVersionOption: '1.11'
              mavenVersionOption: 'Default'
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              failTaskOnMissingResultsFile: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: 'target/*.jar'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              containerRegistry: '$(containerRegistry)'
              repository: '$(imageName)'
              command: 'buildandPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(tag)'