trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: Thivagar007.HTS-L2-CS001
      trigger: true

variables:
  acrLoginServer: htsl2cs01.azurecr.io
  imageName: snakegameapp
  tag: $(resources.pipeline.ciPipeline.runName)

stages:

- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  jobs:
    - deployment: DeployDev
      displayName: 'Deploy to AKS (Dev)'
      environment: 'dev'
      pool:
        name: 'vmss-agent'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - task: FileTransform@1
                displayName: 'Inject image tag into manifest'
                inputs:
                  folderPath: '$(System.DefaultWorkingDirectory)/snakegame/k8s'
                  fileType: 'yaml'
                  targetFiles: 'deployment.yml'

              - task: Kubernetes@1
                displayName: 'Deploy to AKS - Dev'
                inputs:
                  connectionType: 'Kubernetes Service Connection'
                  kubernetesServiceEndpoint: 'HTS-L2-AKS-SC'
                  namespace: 'dev'
                  command: apply
                  useConfigurationFile: true
                  configuration: |
                    ./snakegame/k8s/deployment.yml
                    ./snakegame/k8s/service.yml

- stage: Deploy_Test
  displayName: 'Deploy to Test'
  dependsOn: Deploy_Dev
  condition: succeeded()
  jobs:
    - deployment: DeployTest
      displayName: 'Deploy to AKS (Test)'
      environment: 'test'
      pool:
        name: 'vmss-agent'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - task: FileTransform@1
                displayName: 'Inject image tag into manifest'
                inputs:
                  folderPath: '$(System.DefaultWorkingDirectory)/snakegame/k8s'
                  fileType: 'yaml'
                  targetFiles: 'deployment.yml'

              - task: Kubernetes@1
                displayName: 'Deploy to AKS - Test'
                inputs:
                  connectionType: 'Kubernetes Service Connection'
                  kubernetesServiceEndpoint: 'HTS-L2-AKS-SC'
                  namespace: 'test'
                  command: apply
                  useConfigurationFile: true
                  configuration: |
                    ./snakegame/k8s/deployment.yml
                    ./snakegame/k8s/service.yml

- stage: Deploy_Prod
  displayName: 'Deploy to Prod'
  dependsOn: Deploy_Test
  condition: succeeded()
  jobs:
    - deployment: DeployProd
      displayName: 'Deploy to AKS (Prod)'
      environment: 'prod'
      pool:
        name: 'vmss-agent'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - task: FileTransform@1
                displayName: 'Inject image tag into manifest'
                inputs:
                  folderPath: '$(System.DefaultWorkingDirectory)/snakegame/k8s'
                  fileType: 'yaml'
                  targetFiles: 'deployment.yml'

              - task: Kubernetes@1
                displayName: 'Deploy to AKS - Prod'
                inputs:
                  connectionType: 'Kubernetes Service Connection'
                  kubernetesServiceEndpoint: 'HTS-L2-AKS-SC'
                  namespace: 'prod'
                  command: apply
                  useConfigurationFile: true
                  configuration: |
                    ./snakegame/k8s/deployment.yml
                    ./snakegame/k8s/service.yml
